### ISSUE TITLE
my server cannot activate the plugin please help

### ISSUE THREAD

**Issue by slema20** [Drawethree/PRO-BuildBattle#16]
[13:11:21] [Server thread/ERROR]: Error occurred while enabling BuildBattlePro v6.4.8 (Is it up to date?)
java.lang.ClassFormatError: StackMapTable format error: bad offset for Uninitialized in method me.drawethree.buildbattle.utility.LocationUtil.getCenter(Lorg/bukkit/Location;)Lorg/bukkit/Location;
	at me.drawethree.buildbattle.managers.BBSettings.setMainLobbyLocation(BBSettings.java:480) ~[?:?]
	at me.drawethree.buildbattle.managers.BBSettings.loadSettings(BBSettings.java:712) ~[?:?]
	at me.drawethree.buildbattle.BuildBattle.onEnable(BuildBattle.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at java.lang.Thread.run(Thread.java:748) ?:1.8.0_202
![Captura](https://user-images.githubusercontent.com/69693967/118971940-492b9200-b970-11eb-92b9-fa55290a2493.JPG)

**Comment by slema20** [comment]
version 6.4.7 works but 6.4.8 does not load on the server

**Comment by slema20** [comment]
6.5.0 does not load on the server

**Comment by slema20** [comment]
[13:09:13] [Server thread/ERROR]: Error occurred while enabling BuildBattlePro v6.5.1 (Is it up to date?)
java.lang.ClassFormatError: StackMapTable format error: bad offset for Uninitialized in method me.drawethree.buildbattle.utility.ParticleEffect.display(Lorg/bukkit/util/Vector;FLorg/bukkit/Location;D)V
	at me.drawethree.buildbattle.objects.bbobjects.particle.BBParticle.<clinit>(BBParticle.java:11) ~[?:?]
	at me.drawethree.buildbattle.managers.OptionsManager.loadParticlesInventory(OptionsManager.java:104) ~[?:?]
	at me.drawethree.buildbattle.managers.OptionsManager.reloadItemsAndInventories(OptionsManager.java:88) ~[?:?]
	at me.drawethree.buildbattle.managers.OptionsManager.<init>(OptionsManager.java:68) ~[?:?]
	at me.drawethree.buildbattle.BuildBattle.onEnable(BuildBattle.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by ImYenil** [comment]
Whats your server java version?

**Comment by slema20** [comment]
It working thanks
